### ISSUE TITLE
Bot add musics himself.

### ISSUE THREAD

**Issue by NaNonnI** [DashCruft/Discord.JS-Music-Bot#2]
https://prnt.sc/10asf3g
Andddd.. It's all.

**Comment by Youwho1234567** [comment]
I found this looking for some answers for something else but I use Distube to and its started to add music its weird

**Comment by Darker-Ink** [comment]
> https://prnt.sc/10asf3g
> Andddd.. It's all.

Thats because of Auto Play, All you got to do as add

`.on("initQueue", queue => {
    queue.autoplay = false;
    queue.volume = 50;
})`

**Comment by Youwho1234567** [comment]
where do I add this code?

**Comment by Youwho1234567** [comment]
> > https://prnt.sc/10asf3g
> > Andddd.. It's all.
> 
> Thats because of Auto Play, All you got to do as add
> 
> `.on("initQueue", queue => { queue.autoplay = false; queue.volume = 50; })`

Where  do I add this code

**Comment by p0ryae** [comment]
Disable autoplay and you should be good to go.

Check DisTube documentation:
https://distube.js.org/#/docs/DisTube/stable/class/Queue?scrollTo=autoplay

Also, in the newest version the autoplay seems to be false by default
